import 'package:flutter_places/model/contact_model.dart';
import 'package:flutter_places/model/user_model.dart';

class AppConstants {
  static UserModel currentUser = UserModel();

  ContactModel createContactFromUserModel() {
    return ContactModel(
      id: currentUser.id,
      firstName: currentUser.firstName,
      lastName: currentUser.lastName,
      displayImage: currentUser.displayImage,
    );
  }

  static final Map<int, int> daysInMonths = {
    1: 31,
    2: DateTime.now().year % 4 == 0 ? 29 : 28,
    3: 31,
    4: 30,
    5: 31,
    6: 30,
    7: 31,
    8: 31,
    9: 30,
    10: 31,
    11: 30,
    12: 31,
  };

  static final Map<int, String> monthDict = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December",
  };

  final List<String> cities = [
    'İstanbul',
    'Ankara',
    'İzmir',
    'Bursa',
    'Adana',
    'Antalya',
    'Konya',
    'Gaziantep',
    'Şanlıurfa',
    'Mersin',
    'Diyarbakır',
    'Kayseri',
    'Eskişehir',
    'Samsun',
    'Malatya',
    'Trabzon',
    'Erzurum',
    'Van',
    'Denizli',
    'Balıkesir',
    'Adıyaman',
    'Afyonkarahisar',
    'Ağrı',
    'Amasya',
    'Artvin',
    'Aydın',
    'Bitlis',
    'Bolu',
    'Çanakkale',
    'Çankırı',
    'Çorum',
    'Düzce',
    'Edirne',
    'Elazığ',
    'Erzincan',
    'Giresun',
    'Hakkari',
    'Hatay',
    'Isparta',
    'Kahramanmaraş',
    'Karabük',
    'Karaman',
    'Kars',
    'Kastamonu',
    'Kırıkkale',
    'Kırklareli',
    'Kilis',
    'Kütahya',
    'Mardin',
    'Muğla',
    'Muş',
    'Nevşehir',
    'Niğde',
    'Ordu',
    'Rize',
    'Sakarya',
    'Siirt',
    'Sinop',
    'Sivas',
    'Tekirdağ',
    'Tokat',
    'Uşak',
    'Yalova',
    'Yozgat',
    'Zonguldak',
    'Aksaray',
    'Bayburt',
    'Bilecik',
    'Bingöl',
    'Burdur',
    'Iğdır',
    'Kırşehir',
    'Osmaniye',
    'Şırnak',
    'Tunceli',
    'Bartın',
    'Ardahan',
    'Yalova',
    'Karabük',
    'Kilis',
    'Osmaniye',
    'Düzce',
  ];
}
